name: SmartTrim
id: smarttrim
author_link: http://ubiquitic.com/
author_name: François Nonnenmacher, Ubiquitic
plugin_link: http://ubiquitic.com/software/smarttrim-movable-type-plugin.html
description: <__trans phrase="A global modifier to trim strings by length without cutting words.">
version: 2.0
tags:
    modifier:
        smarttrim:
            label: smarttrim
            handler: $SmartTrim::SmartTrim::Plugin::smarttrim
l10n_class: SmartTrim::L10N
